
services:
  app-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:${NODE_VERSION:-22.15.0-alpine3.21} 
    working_dir: /app-front
    volumes:
      - .:/app-front
      # Anonymous volume:
      - /app-front/node_modules
    ports:
      - "8081:3000"
    environment:
      - PORT=3000
      - DATABASE_HOST=backend-ecoride-mysql-1
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    command: ["node", "index.js"]
    networks:
      - app-network

networks:
  app-network:
