# fly.toml app configuration file generated for frontend-ecoride on 2025-05-30T13:25:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-ecoride'
primary_region = 'cdg'

[build]

[env]
  DATABASE_HOST = "ecoride-mysql-internal.internal"
  DATABASE_USER = "studi_ecoride"
  DATABASE_NAME = "ecoride_db"
  DATABASE_PORT = "3306"

[http_service]
  internal_port = 4500
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
